name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Instalar dependências
        run: go mod download

      - name: Rodar Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2

      - name: Rodar Testes
        run: go test -v ./...

      - name: Gerar Coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Publicar Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Build
        run: go build -v ./...
